# Generated by Django 3.2.19 on 2023-05-24 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0002_auto_20230524_0007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='measurements',
        ),
        migrations.AddField(
            model_name='measurement',
            name='sensor',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='sensor', to='measurement.sensor'),
            preserve_default=False,
        ),
    ]
